import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Layout } from "../../features/Layout";

const Welcome: NextPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Welcome Personal Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <>
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Welcome to our <span className="text-accent">{"TODO"}</span>, DAO;
              Please stake <span className="text-accent">1 DAI</span>, into our
              community pool to generate yield for local development
            </h1>
            <button
              className="mw-50 btn-accent btn"
              onClick={() => {
                router.push("/welcome");
              }}
            >
              Join DAO
            </button>
          </>
        </div>
      </Layout>
    </>
  );
};

export default Welcome;
